# Generating stratified samples of the data from Q4 2022 and Q1 2023 of Citibike NYC

## 1. Initialising and importing the original data:

Read the original CSV files, which were downloaded from https://s3.amazonaws.com/tripdata/index.html, as Pandas DataFrames and specified the right dtypes for each column.

In [1]:
# Imported all the dependencies:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Read the original Citibike CSV files with Pandas and created a DataFrame for each one of them by specifying the dtypes for
# each column:
cols_dtypes_d = {'ride_id': 'object',
                    'rideable_type': 'object',
                    'start_station_name': 'object',
                    'start_station_id': 'object',
                    'end_station_name': 'object',
                    'end_station_id': 'object',
                    'start_lat': 'float64',
                    'start_lng': 'float64',
                    'end_lat': 'float64',
                    'end_lng': 'float64',
                    'member_casual': 'object'}
date_cols_l = ['started_at',
                'ended_at']

oct_df = pd.read_csv('202210-citibike-tripdata.csv', dtype=cols_dtypes_d, parse_dates=date_cols_l)
nov_df = pd.read_csv('202211-citibike-tripdata.csv', dtype=cols_dtypes_d, parse_dates=date_cols_l)
dec_df = pd.read_csv('202212-citibike-tripdata.csv', dtype=cols_dtypes_d, parse_dates=date_cols_l)
jan_df = pd.read_csv('202301-citibike-tripdata.csv', dtype=cols_dtypes_d, parse_dates=date_cols_l)
feb_df = pd.read_csv('202302-citibike-tripdata.csv', dtype=cols_dtypes_d, parse_dates=date_cols_l)
mar_df = pd.read_csv('202303-citibike-tripdata.csv', dtype=cols_dtypes_d, parse_dates=date_cols_l)

# Showed one of the created DataFrames to check there were no errors:
oct_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2CF35A89B21C6E3C,classic_bike,2022-10-24 14:30:25,2022-10-24 14:37:35,St. Nicholas Ave & W 126 St,7756.10,Amsterdam Ave & W 136 St,7920.05,40.811388,-73.951995,40.819746,-73.951819,member
1,291CC2C6D361C2DA,classic_bike,2022-10-30 03:53:38,2022-10-30 03:57:57,Stuyvesant Ave & Gates Ave,4458.06,Halsey St & Tompkins Ave,4319.07,40.688445,-73.933195,40.682369,-73.944118,member
2,80192DC8429B07EE,classic_bike,2022-10-08 15:03:06,2022-10-08 15:17:13,Broadway & Berry St,5164.05,Meserole Ave & Manhattan Ave,5666.04,40.710361,-73.965304,40.727086,-73.952991,member
3,D214E550C317C65E,classic_bike,2022-10-18 08:32:04,2022-10-18 08:36:41,W 84 St & Columbus Ave,7382.04,W 76 St & Columbus Ave,7281.09,40.785000,-73.972834,40.780184,-73.977285,member
4,2D23E8BAE75AA184,classic_bike,2022-10-26 08:00:40,2022-10-26 08:10:27,Pike St & Monroe St,5159.04,Broad St & Bridge St,4962.08,40.711731,-73.991930,40.703652,-74.011678,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021665,EB791C76AD3E012D,classic_bike,2022-10-20 11:13:29,2022-10-20 11:23:26,Clinton St & Union St,4266.03,3 St & 3 Ave,4028.03,40.683116,-73.997853,40.675070,-73.987752,member
3021666,B57BDF2A6FA4BA26,classic_bike,2022-10-10 18:36:52,2022-10-10 18:59:03,E 35 St & Madison Ave,6398.08,Central Park West & W 68 St,7079.06,40.748480,-73.982556,40.773407,-73.977825,member
3021667,412A5ADB8EE05B8D,classic_bike,2022-10-25 18:19:19,2022-10-25 18:35:42,Nassau St\t& Duffield St,4781.05,West St & Liberty St,5184.08,40.698374,-73.983878,40.711444,-74.014847,member
3021668,FB3AA7F68A0489ED,classic_bike,2022-10-30 13:53:08,2022-10-30 13:55:52,21 St & Hoyt Ave S,7126.01,24 Ave & 26 St,7152.10,40.774751,-73.923553,40.774591,-73.918544,member
3021669,91177E95D3937743,classic_bike,2022-10-26 16:56:11,2022-10-26 17:01:28,Park Pl & Church St,5288.08,West St & Liberty St,5184.08,40.713342,-74.009355,40.711444,-74.014847,member

## 2. Sampling the data:

???
Read the original CSV files, which were downloaded from https://s3.amazonaws.com/tripdata/index.html, as Pandas DataFrames and specified the right dtypes for each column.

In [3]:
# Filtered each DataFrame by keeping only the rows that had positive durations and created new DataFrames:
positive_durations_oct_df = oct_df.loc[oct_df[date_cols_l[1]] > oct_df[date_cols_l[0]]].copy()
positive_durations_nov_df = nov_df.loc[nov_df[date_cols_l[1]] > nov_df[date_cols_l[0]]].copy()
positive_durations_dec_df = dec_df.loc[dec_df[date_cols_l[1]] > dec_df[date_cols_l[0]]].copy()
positive_durations_jan_df = jan_df.loc[jan_df[date_cols_l[1]] > jan_df[date_cols_l[0]]].copy()
positive_durations_feb_df = feb_df.loc[feb_df[date_cols_l[1]] > feb_df[date_cols_l[0]]].copy()
positive_durations_mar_df = mar_df.loc[mar_df[date_cols_l[1]] > mar_df[date_cols_l[0]]].copy()

# Showed one of the filtered DataFrames to check there were no errors:
positive_durations_oct_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2CF35A89B21C6E3C,classic_bike,2022-10-24 14:30:25,2022-10-24 14:37:35,St. Nicholas Ave & W 126 St,7756.10,Amsterdam Ave & W 136 St,7920.05,40.811388,-73.951995,40.819746,-73.951819,member
1,291CC2C6D361C2DA,classic_bike,2022-10-30 03:53:38,2022-10-30 03:57:57,Stuyvesant Ave & Gates Ave,4458.06,Halsey St & Tompkins Ave,4319.07,40.688445,-73.933195,40.682369,-73.944118,member
2,80192DC8429B07EE,classic_bike,2022-10-08 15:03:06,2022-10-08 15:17:13,Broadway & Berry St,5164.05,Meserole Ave & Manhattan Ave,5666.04,40.710361,-73.965304,40.727086,-73.952991,member
3,D214E550C317C65E,classic_bike,2022-10-18 08:32:04,2022-10-18 08:36:41,W 84 St & Columbus Ave,7382.04,W 76 St & Columbus Ave,7281.09,40.785000,-73.972834,40.780184,-73.977285,member
4,2D23E8BAE75AA184,classic_bike,2022-10-26 08:00:40,2022-10-26 08:10:27,Pike St & Monroe St,5159.04,Broad St & Bridge St,4962.08,40.711731,-73.991930,40.703652,-74.011678,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3021665,EB791C76AD3E012D,classic_bike,2022-10-20 11:13:29,2022-10-20 11:23:26,Clinton St & Union St,4266.03,3 St & 3 Ave,4028.03,40.683116,-73.997853,40.675070,-73.987752,member
3021666,B57BDF2A6FA4BA26,classic_bike,2022-10-10 18:36:52,2022-10-10 18:59:03,E 35 St & Madison Ave,6398.08,Central Park West & W 68 St,7079.06,40.748480,-73.982556,40.773407,-73.977825,member
3021667,412A5ADB8EE05B8D,classic_bike,2022-10-25 18:19:19,2022-10-25 18:35:42,Nassau St\t& Duffield St,4781.05,West St & Liberty St,5184.08,40.698374,-73.983878,40.711444,-74.014847,member
3021668,FB3AA7F68A0489ED,classic_bike,2022-10-30 13:53:08,2022-10-30 13:55:52,21 St & Hoyt Ave S,7126.01,24 Ave & 26 St,7152.10,40.774751,-73.923553,40.774591,-73.918544,member
3021669,91177E95D3937743,classic_bike,2022-10-26 16:56:11,2022-10-26 17:01:28,Park Pl & Church St,5288.08,West St & Liberty St,5184.08,40.713342,-74.009355,40.711444,-74.014847,member

In [4]:
# Dropped all the rows with null values:
positive_durations_dfs = [positive_durations_oct_df,
                          positive_durations_nov_df,
                          positive_durations_dec_df,
                          positive_durations_jan_df,
                          positive_durations_feb_df,
                          positive_durations_mar_df]

for df in positive_durations_dfs:
    df = df.dropna()

# Used 'train_test_split' to randomly sample 1% of the rows of each DataFrames while stratifying by the 'rideable_type' and
# 'member_casual' columns; set a random seed to be able to replicate the results:
stratifying_cols_l = ['rideable_type', 'member_casual']
train_size = 0.01
random_state = 39014

test_positive_durations_oct_df, train_positive_durations_oct_df = train_test_split(positive_durations_oct_df,
                                                                                    train_size=train_size,
                                                                                    random_state=random_state,
                                                                                    stratify=positive_durations_oct_df[
                                                                                        stratifying_cols_l])
test_positive_durations_nov_df, train_positive_durations_nov_df = train_test_split(positive_durations_nov_df,
                                                                                    train_size=train_size,
                                                                                    random_state=random_state,
                                                                                    stratify=positive_durations_nov_df[
                                                                                        stratifying_cols_l])
test_positive_durations_dec_df, train_positive_durations_dec_df = train_test_split(positive_durations_dec_df,
                                                                                    train_size=train_size,
                                                                                    random_state=random_state,
                                                                                    stratify=positive_durations_dec_df[
                                                                                        stratifying_cols_l])
test_positive_durations_jan_df, train_positive_durations_jan_df = train_test_split(positive_durations_jan_df,
                                                                                    train_size=train_size,
                                                                                    random_state=random_state,
                                                                                    stratify=positive_durations_jan_df[
                                                                                        stratifying_cols_l])
test_positive_durations_feb_df, train_positive_durations_feb_df = train_test_split(positive_durations_feb_df,
                                                                                    train_size=train_size,
                                                                                    random_state=random_state,
                                                                                    stratify=positive_durations_feb_df[
                                                                                        stratifying_cols_l])
test_positive_durations_mar_df, train_positive_durations_mar_df = train_test_split(positive_durations_mar_df,
                                                                                    train_size=train_size,
                                                                                    random_state=random_state,
                                                                                    stratify=positive_durations_mar_df[
                                                                                        stratifying_cols_l])

# Showed one of the sampled DataFrames to check there were no errors:
test_positive_durations_oct_df

## HERE

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
418174,A96552B57D555977,classic_bike,2022-10-06 19:15:26,2022-10-06 19:18:23,Frederick Douglass Blvd & W 117 St,7688.12,St Nicholas Ave & Manhattan Ave,7723.01,40.805159,-73.954692,40.809725,-73.953149,member
1453995,26B3266F74CD7015,classic_bike,2022-10-17 17:08:04,2022-10-17 17:11:08,5 Ave & E 87 St,7323.09,E 91 St & Park Ave,7344.05,40.782323,-73.959875,40.783502,-73.955327,member
44741,D0C3CD879269DF5C,classic_bike,2022-10-21 21:04:22,2022-10-21 21:25:51,MacDougal St & Prince St,5687.04,Gramercy Park N & Gramercy Park E,6013.12,40.727103,-74.002971,40.737950,-73.985090,member
2106431,C1A9A329B1D93DBB,classic_bike,2022-10-02 19:06:49,2022-10-02 19:10:36,E 6 St & Avenue B,5584.04,E 9 St & Avenue C,5616.01,40.724537,-73.981854,40.725213,-73.977688,member
1110131,17740521CB9F413B,classic_bike,2022-10-06 18:03:48,2022-10-06 18:09:55,North Moore St & Greenwich St,5470.12,Vesey St & Church St,5216.06,40.720195,-74.010301,40.712220,-74.010472,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347905,041B4FA38F3BF9C8,classic_bike,2022-10-10 18:12:54,2022-10-10 18:20:15,Lenox Ave & W 146 St,7910.10,W 135 St & Lenox Terrace Pl,7832.04,40.821111,-73.935971,40.813619,-73.939336,casual
2750278,3D385FB95430D54C,classic_bike,2022-10-17 11:19:50,2022-10-17 11:32:57,E 78 St & 2 Ave,7057.07,Central Park W & W 97 St,7538.18,40.772797,-73.955778,40.792495,-73.964171,member
2395630,225E3F46CCE72AE3,classic_bike,2022-10-27 12:11:07,2022-10-27 12:12:36,Barrow St & Hudson St,5805.05,Christopher St & Greenwich St,5847.01,40.731724,-74.006744,40.732916,-74.007114,member
628817,F6DED66414349A07,electric_bike,2022-10-06 16:09:26,2022-10-06 16:10:21,Greene St & Prince St,5602.06,Greene St & Prince St,5602.06,40.725117,-73.999305,40.725117,-73.999305,member
1249619,D4014C6C60AD7482,classic_bike,2022-10-23 14:13:10,2022-10-23 14:34:52,Nassau Ave & Newell St,5623.03,Bleecker St & Crosby St,5679.08,40.724771,-73.947555,40.726156,-73.995102,member

In [30]:
# Concatenated the sampled January, February, and March DataFrames and reset the index:
frames = [test_positive_durations_oct_df,
          test_positive_durations_nov_df,
          test_positive_durations_dec_df,
          test_positive_durations_jan_df,
          test_positive_durations_feb_df,
          test_positive_durations_mar_df]
final_df = pd.concat(frames)
final_df = final_df.reset_index(drop=True)
final_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C017E3217071D901,classic_bike,2022-10-04 07:25:56,2022-10-04 07:38:50,1 Ave & E 62 St,6753.08,E 47 St & Park Ave,6584.12,40.761227,-73.960940,40.755103,-73.974987,member
1,2F4F558C62DB06FB,classic_bike,2022-10-26 21:32:22,2022-10-26 21:51:55,6 Ave & W 33 St,6364.07,E 39 St & 2 Ave,6345.08,40.749013,-73.988484,40.748033,-73.973828,member
2,6DC1B28A2D485DDF,classic_bike,2022-10-17 17:13:13,2022-10-17 17:24:31,Stanhope St & Fairview Ave,5146.03,Evergreen Ave & Noll St,4873.08,40.709980,-73.911160,40.701060,-73.933180,member
3,66D964F68275E3C1,classic_bike,2022-10-03 12:34:53,2022-10-03 12:37:01,Old Broadway & W 133 St,7881.09,Broadway & W 133 St,7903.02,40.818212,-73.955277,40.819034,-73.956156,member
4,C44EE20D2DF20BF7,classic_bike,2022-10-23 10:00:29,2022-10-23 10:15:00,44 St & 48 Ave,6058.08,Queens Plaza North & Crescent St,6429.01,40.739414,-73.921320,40.751102,-73.940737,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
128937,0243CBCAF7B30F8F,classic_bike,2023-03-04 16:37:40,2023-03-04 16:50:43,Bergen St & Vanderbilt Ave,4157.10,Degraw St & Hoyt St,4258.07,40.679439,-73.968044,40.681990,-73.990790,member
128938,8F2FA9ECF567717E,classic_bike,2023-03-01 19:01:05,2023-03-01 19:03:30,E 53 St & Lexington Ave,6617.09,E 54 St & 1 Ave,6608.09,40.758742,-73.970543,40.756265,-73.964179,member
128939,6D094B8931D2B8BE,classic_bike,2023-03-09 15:26:06,2023-03-09 15:33:04,Central Park West & W 68 St,7079.06,E 68 St & 3 Ave,6896.16,40.773386,-73.977734,40.767128,-73.962246,member
128940,3C8CE2853564ED33,classic_bike,2023-03-16 08:30:46,2023-03-16 08:35:24,W 44 St & 5 Ave,6551.02,W 56 St & 6 Ave,6809.07,40.754823,-73.980319,40.763406,-73.977225,member
128941,38E13952C69F6611,classic_bike,2023-03-22 15:40:52,2023-03-22 15:51:02,E 27 St & 1 Ave,6004.06,W 27 St & 7 Ave,6247.06,40.739445,-73.976806,40.746647,-73.993915,member

In [31]:
import numpy as np

final_df['month_year'] = final_df['started_at'].dt.month
final_df['month_year'] = final_df['month_year'].replace(10, 'October 2022')\
    .replace(11, 'November 2022')\
    .replace(12, 'December 2022')\
    .replace(1, 'January 2023')\
    .replace(2, 'February 2023')\
    .replace(3, 'March 2023')
final_df['d_month_year'] = pd.to_datetime(final_df['started_at']).dt.to_period('M')
final_df['duration'] = final_df['ended_at'] - final_df['started_at']
d = pd.to_timedelta(final_df['duration']).dt.components[['days', 'hours', 'minutes', 'seconds']]
d['hours'] = d['hours'].add(d.pop('days') * 24)
final_df['final_duration'] = d.astype(str).agg(lambda s: ':'.join(s.str.zfill(2)), axis=1)
final_df['quarter'] = np.where(final_df['d_month_year'] < '2023-01', 'Q4 2022', 'Q1 2023')
final_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month_year,d_month_year,duration,final_duration,quarter
0,C017E3217071D901,classic_bike,2022-10-04 07:25:56,2022-10-04 07:38:50,1 Ave & E 62 St,6753.08,E 47 St & Park Ave,6584.12,40.761227,-73.960940,40.755103,-73.974987,member,October 2022,2022-10,0 days 00:12:54,00:12:54,Q4 2022
1,2F4F558C62DB06FB,classic_bike,2022-10-26 21:32:22,2022-10-26 21:51:55,6 Ave & W 33 St,6364.07,E 39 St & 2 Ave,6345.08,40.749013,-73.988484,40.748033,-73.973828,member,October 2022,2022-10,0 days 00:19:33,00:19:33,Q4 2022
2,6DC1B28A2D485DDF,classic_bike,2022-10-17 17:13:13,2022-10-17 17:24:31,Stanhope St & Fairview Ave,5146.03,Evergreen Ave & Noll St,4873.08,40.709980,-73.911160,40.701060,-73.933180,member,October 2022,2022-10,0 days 00:11:18,00:11:18,Q4 2022
3,66D964F68275E3C1,classic_bike,2022-10-03 12:34:53,2022-10-03 12:37:01,Old Broadway & W 133 St,7881.09,Broadway & W 133 St,7903.02,40.818212,-73.955277,40.819034,-73.956156,member,October 2022,2022-10,0 days 00:02:08,00:02:08,Q4 2022
4,C44EE20D2DF20BF7,classic_bike,2022-10-23 10:00:29,2022-10-23 10:15:00,44 St & 48 Ave,6058.08,Queens Plaza North & Crescent St,6429.01,40.739414,-73.921320,40.751102,-73.940737,member,October 2022,2022-10,0 days 00:14:31,00:14:31,Q4 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128937,0243CBCAF7B30F8F,classic_bike,2023-03-04 16:37:40,2023-03-04 16:50:43,Bergen St & Vanderbilt Ave,4157.10,Degraw St & Hoyt St,4258.07,40.679439,-73.968044,40.681990,-73.990790,member,March 2023,2023-03,0 days 00:13:03,00:13:03,Q1 2023
128938,8F2FA9ECF567717E,classic_bike,2023-03-01 19:01:05,2023-03-01 19:03:30,E 53 St & Lexington Ave,6617.09,E 54 St & 1 Ave,6608.09,40.758742,-73.970543,40.756265,-73.964179,member,March 2023,2023-03,0 days 00:02:25,00:02:25,Q1 2023
128939,6D094B8931D2B8BE,classic_bike,2023-03-09 15:26:06,2023-03-09 15:33:04,Central Park West & W 68 St,7079.06,E 68 St & 3 Ave,6896.16,40.773386,-73.977734,40.767128,-73.962246,member,March 2023,2023-03,0 days 00:06:58,00:06:58,Q1 2023
128940,3C8CE2853564ED33,classic_bike,2023-03-16 08:30:46,2023-03-16 08:35:24,W 44 St & 5 Ave,6551.02,W 56 St & 6 Ave,6809.07,40.754823,-73.980319,40.763406,-73.977225,member,March 2023,2023-03,0 days 00:04:38,00:04:38,Q1 2023
128941,38E13952C69F6611,classic_bike,2023-03-22 15:40:52,2023-03-22 15:51:02,E 27 St & 1 Ave,6004.06,W 27 St & 7 Ave,6247.06,40.739445,-73.976806,40.746647,-73.993915,member,March 2023,2023-03,0 days 00:10:10,00:10:10,Q1 2023

In [32]:
final_df.min()

ride_id                  0000196E1FAF6045
rideable_type                classic_bike
started_at            2022-10-01 00:02:50
ended_at              2022-10-01 00:07:46
start_station_name       1 Ave & E 110 St
start_station_id                  2733.03
end_station_name         1 Ave & E 110 St
end_station_id                    2733.03
start_lat                       40.633385
start_lng                      -74.026823
end_lat                         40.633385
end_lng                        -74.086701
member_casual                      casual
month_year                  December 2022
d_month_year                      2022-10
duration                  0 days 00:00:01
final_duration                   00:00:01
quarter                           Q1 2023
dtype: object

In [33]:
final_df.dtypes

ride_id                        object
rideable_type                  object
started_at             datetime64[ns]
ended_at               datetime64[ns]
start_station_name             object
start_station_id               object
end_station_name               object
end_station_id                 object
start_lat                     float64
start_lng                     float64
end_lat                       float64
end_lng                       float64
member_casual                  object
month_year                     object
d_month_year                period[M]
duration              timedelta64[ns]
final_duration                 object
quarter                        object
dtype: object

In [34]:
# Converted the concatenated DataFrame into a CSV file:
final_df.to_csv('stratified-sampled-Q42022-Q12023.csv')